config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    # before_save { self.email = self.email.downcase } ^^^^equivalent formulation
    # before_save { email.downcase! } ^^^^equivalent formulation
    validates(:name, presence: true, length: {maximum: 50})
    # validates :name, presence: true  ^^^^equivalent formulation
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :email, 
        presence: true, 
        length: {maximum: 255}, 
        format: { with: VALID_EMAIL_REGEX }, 
        uniqueness: true
 
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    # class << self
    #     def digest(string)
    #         cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :  BCrypt::Engine.cost
    #         BCrypt::Password.create(string, cost: cost)
    #     end

    #     def new_token
    #         SecureRandom.urlsafe_base64
    #     end
    # end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
        remember_digest
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

    def session_token
        remember_digest || remember
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # include ApplicationHelper
    def hello
        render html: "hello, world!"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      # remember(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      # redirect_to @user
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end        
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def remember(user)
        user.remember
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def log_in(user)
        session[:user_id] = user.id
        session[:session_token] = user.session_token
    end

    def current_user
        if (user_id = session[:user_id])
            user = User.find_by(id: user_id)
            if user && session[:session_token] == user.session_token
                @current_user ||= User.find_by(id: session[:user_id])
            end
        elsif (user_id = cookies.encrypted[:user_id])
            raise
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def forget
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        reset_session
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options =  { size: 80 })
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.haml
%footer{ :class => 'footer' }
    %small
        The
        %a{ :href => 'https://www.railstutorial.org/'} Ruby on Rails Tutorial
        by
        %a{ :href => 'https://www.michaelhartl.com/'} Michael Hartl
    %nav
        %ul{:class => 'nav navbar-nav navbar-right'}
            %li
                =link_to 'About', about_path

            
            %li
                =link_to 'Contact', contact_path

            %li
                %a{:href=> 'https://news.railstutorial.org/'} Ruby News

app/views/layouts/_header.html.haml
%header{:class => 'navbar navbar-fixed-top navbar-inverse' }
    %div{:class => 'container'}
        %a{:href => root_path, :id => 'logo'} Sample App
        %nav
            %div{:class => 'navbar-header'}
                %button{ :type => 'button', :class => 'navbar-toggle collapsed', 'data-toggle' => 'collapse', 'data-target' => '#bs-example-navbar-collapse-1', 'aria-expanded' => 'false', 'aria-controls' => 'bs-example-navbar-collapse-1'}
                    %span{ :class => 'sr-only'} Toggle Navigation
                    %span{ :class => 'icon-bar'}
                    %span{ :class => 'icon-bar'}
                    %span{ :class => 'icon-bar'}
            %div{:class => 'collapse navbar-collapse', :id => 'bs-example-navbar-collapse-1'}
                %ul{:class => 'nav navbar-nav navbar-right'}
                    %li
                        =link_to 'Home', root_path
                    
                    %li
                        =link_to 'Help', help_path
                    %li
                        =link_to 'Log In', login_path
                    - if logged_in?
                        %li
                            =link_to 'Users', '#'
                        %li{:class => 'dropwdown'}
                            %a{ :href => "#", :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'}
                                Account
                                %b{:class => 'caret'}
                            %ul{:class => 'dropdown-menu'}
                                %li
                                    =link_to 'Profile', current_user
                                %li
                                    =link_to 'Settings', edit_user_path
                                %div{:class => 'divider '}
                                %li
                                    =link_to 'Log out', root_path, :method => :delete

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
    %div{:id => 'error_explanation', :role => 'alert'}
        %div{:class => 'alert alert-danger'}
            The form contains #{pluralize(@user.errors.count, 'error')}
        %ul
            - @user.errors.full_messages.each do |msg|
                %li #{msg}

app/views/static_pages/about.html.haml
- content_for :title, 'About'

%h1 About
%p
    The
    %a{ :href => "https://www.railstutorial.org/"}
        %em Ruby on Rails Tutorial,
    a part of 
    
    %a{ :href => "https://www.learnenough.com/"} Learn Enough
    family of tutorials, is a
    %a{ :href => "https://www.railstutorial.org/book"} book
    and
    %a{ :href => "https://screencasts.railstutorial.org/"} screencast series
    to teach web development with
    %a{ :href => "https://rubyonrails.org/"} Ruby on Rails.
    This is the sample app for the tutorial.

app/views/static_pages/contact.html.haml
- content_for :title, 'Contact'

%h1 Contact
%p
    Contact the Ruby on Rails Tutorial about the sample app at the
    %a{ :href => "https://www.railstutorial.org/contact"}
        %em contact page
    :plain
        .

    
 

app/views/static_pages/help.html.haml
- content_for :title, 'Help'

%h1 Help

%p 
    Get help on the Ruby on Rails Tutorial at the
    %a{ :href => "https://www.railstutorial.org/help"} Rails Tutorial help page.
    To get help on this sample app, see the
    %a{ :href => "https://www.railstutorial.org/book"}
        %em Ruby on Rails Tutorial book.

app/views/static_pages/home.html.haml
%div{:class=> "center jumbotron"}
    %h1 Welcome to the Sample App
    %h2
        This is the home page for the
        %a{ :href => "https://www.railstutorial.org/" } Ruby on Rails Tutorial
        
            
    = link_to 'Sign up now!', signup_path, :class => "btn btn-lg btn-primary" 
= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" 
-# = link_to image_tag("kitten.jpg", alt: "Kitten", width: "400"), "https://en.wikipedia.org/wiki/Kitten" 

app/views/users/edit.html.haml
- content_for :title, 'Update your profile'

%h1 Update your profile

%div{:class => "row"}
    %div{:class => "col-md-6 col-md-offset-3"}
        = form_with(model: @user, local: true, class: 'new_user', id: 'new_user') do |f|
            = render 'shared/error_messages'
            = f.label :name
            = f.text_field :name, :class => 'form-control'

            = f.label :email
            = f.email_field :email, :class => 'form-control'

            = f.label :password
            = f.password_field :password, :class => 'form-control'

            = f.label :password_confirmation, "Confirmation"
            = f.password_field :password_confirmation, :class => 'form-control'
    
            = f.submit "Save changes", :class => 'btn btn-primary'
        %div{:class => 'gravatar_edit'}
            = gravatar_for(@user)
            %a{:href => 'https://gravatar.com/emails', :target => '_blank'} Change

app/views/users/new.html.haml
- content_for :title, 'Sign up'

%h1 Sign up

%div{:class => "row"}
    %div{:class => "col-md-6 col-md-offset-3"}
        = form_with(model: @user, local: true, class: 'new_user', id: 'new_user') do |f|
            = render 'shared/error_messages'
            = f.label :name
            = f.text_field :name, :class => 'form-control'

            = f.label :email
            = f.email_field :email, :class => 'form-control'

            = f.label :password
            = f.password_field :password, :class => 'form-control'

            = f.label :password_confirmation, "Confirmation"
            = f.password_field :password_confirmation, :class => 'form-control'
    
            = f.submit "Create my account", :class => 'btn btn-primary'
        %p
            Already have an account? 
            = link_to 'Login now!', login_path

app/views/users/show.html.haml
- content_for :title, @user.name

%div{:class => "row"}
    %aside{:class => "col-md-4"}
        %section{:class => "user_info"}
            %h1 
                #{gravatar_for @user}
                #{@user.name}